### ISSUE TITLE
Changing adapter

### ISSUE THREAD

**Issue by yoramdelangen** [Rekord/rekord-storkjs#4]
Is there a way to change the StorkJS adapter?

**Comment by ClickerMonkey** [comment]
The options you pass to Rekord are also passed to StorkJS. StorkJS and Rekord both use the name property - StorkJS has an added property called `adapter` which you can pass to Rekord like a normal option.

**Comment by yoramdelangen** [comment]
Sweet! In this case it's pretty easy to create a custom adapter for StorkJS to handle a Sqlite database.

I'm using Rekord for an Ionic App, but it's currently not "keeping" my data after I completely close the app, because the non-persistence database.

Consider this issue as fixed/done :)

**Comment by ClickerMonkey** [comment]
That's odd that it wasn't keeping your data - is there something special about ionic apps? StorkJS should've persisted everything just fine to local storage - already using an sqlite adapter if your browser supports it.

**Comment by yoramdelangen** [comment]
I've been running an Ionic App on my iPhone and it is storing the data in the database. But after I clean the app from memory and reopen the app it's starting a new 'session'. I basicly do not use a browser.

**Comment by ClickerMonkey** [comment]
Ah okay - I'll mark this as resolved as requested.
